import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trainers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        Home
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
