import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/login'
import Menu from './user/user-menu'
import Inbody from './user/user-menu/inbody'
import Detail from './user/user-session/detail'
import Session from './user/user-session'
import Main from './user/main'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Trainers</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Login />

			<main className="flex justify-center">
				<div className="max-w-[800px] border p-2 w-full">Home..</div>
			</main>
			<Session />
			<footer></footer>
		</div>
	)
}

export default Home
